---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    # Can be any supported provider (virtualbox, parallels, libvirt, etc)
    name: virtualbox
lint: |
  set -e
  ansible-lint .
platforms:
  - name: ubuntu20
    config_options:
      ssh.keep_alive: true
      ssh.remote_user: 'vagrant'
      synced_folder: false
      cachier: false
      vm.boot_timeout: 600
    box: ubuntu/focal64
    # box_version: 32.20200422.0
    memory: "512"
    cpus: "1"
  - name: centos8
    config_options:
      ssh.keep_alive: true
      ssh.remote_user: 'vagrant'
      synced_folder: false
      cachier: false
      vm.boot_timeout: 600
    box: centos/8
    # box_version: 32.20200422.0
    memory: "512"
    cpus: "1"

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        agent_installer_client_id: ${APPDYNAMICS_API_CLIENT_ID}
        agent_installer_client_secret: ${APPDYNAMICS_API_CLIENT_SECRET}
        agent_installer_access_key: ${APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY:-dummykey}
        agent_installer_controller_url: ${APPDYNAMICS_CONTROLLER_URL}
        agent_installer_account_name: ${APPDYNAMICS_AGENT_ACCOUNT_NAME}
        agent_installer_application_name: agent-installer-ansible-github-test
        agent_installer_temp_local_dir: /tmp/appdynamics-agent-installer
  playbooks:
    prepare: prepare.yaml
    cleanup: cleanup.yaml
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: ansible
