# agent_installer_proxy_host
# agent_installer_proxy_port
agent_installer_enable_proxy: False

agent_installer_install_path: "{{ '/opt/appdynamics/zeroagent' if agent_installer_user == 'root' else ansible_env.HOME }}"
#agent_installer_stage_dir: /tmp/.appdynamics-agent_installer
agent_installer_enable_systemd: True

# Install as sudo or as user
agent_installer_user: root

# panic fatal error warning info debug trace
agent_installer_log_level: info


agent_installer_temp_local_dir: /tmp/appdynamics-agent-installer
agent_installer_stage_dir_prefix: /tmp/appdynamics-agent-installer-stage

# Set to False to skip post install validations
agent_installer_validate_install: True

# Download mode

# remote(directlry to hosts) or local(via ansible controller)
agent_installer_download_mode: local
# set to False to disable download alltogether
agent_installer_download: True