---
- name: Converge
  hosts: all
  vars:
    appdynamics_zeroagent_temp_local_dir: /tmp/.appdynamics-zeroagent
    appdynamics_zeroagent_stage_dir: /tmp/zeroagent-stage
    application_name: vzhuravlev-zfi-ansible
  tasks:
    - name: Ensure target dir is present # and empty( add absent)
      run_once: yes
      delegate_to: localhost
      file:
        path: "{{ appdynamics_zeroagent_temp_local_dir }}"
        state: "{{ item }}"
        mode: 0775
      with_items:
          # - absent
          - directory

    - name: Download
      run_once: yes
      delegate_to: localhost
      register: download_cmd
      appdynamics.zeroagent.download_cmd:
        client_id: "{{ client_id }}"
        client_secret: "{{ client_secret }}"
        controller_url: "{{ controller_url }}"
        dest: "{{ appdynamics_zeroagent_temp_local_dir }}"
      #check_mode: yes

    # - name: Clean remote stage dir
    #   beomce
    #   file:
    #     path: "{{ appdynamics_zeroagent_stage_dir }}"
    #     state: "{{ item }}"
    #     mode: 0775
    #   with_items:
    #       - absent
    #       - directory
    #   # when: download_cmd.changed

    - name: Copy files to hosts
      copy:
        src: "{{ appdynamics_zeroagent_temp_local_dir }}/"
        dest: "{{ appdynamics_zeroagent_stage_dir }}"

    - name: Install zeroagent
      import_role:
        name: appdynamics.zeroagent.install
      tags: molecule-idempotence-notest
