- name: Install zfi agents
  hosts: vagrant
  vars:
    agent_installer_temp_local_dir: /tmp/.appdynamics-agent_installer
    agent_installer_stage_dir: /tmp/agent_installer-stage
  tasks:
    - name: Ensure target dir is present # and empty( add absent)
      run_once: yes
      delegate_to: localhost
      file:
        path: "{{ agent_installer_temp_local_dir }}"
        state: "{{ item }}"
        mode: 0775
      with_items:
          # - absent
          - directory

    - name: Download
      run_once: yes
      delegate_to: localhost
      register: download
      appdynamics.agent_installer.download:
        client_id: "{{ client_id }}"
        client_secret: "{{ client_secret }}"
        controller_url: "{{ controller_url }}"
        dest: "{{ agent_installer_temp_local_dir }}"
      #check_mode: yes

    # - name: Clean remote stage dir
    #   beomce
    #   file:
    #     path: "{{ agent_installer_stage_dir }}"
    #     state: "{{ item }}"
    #     mode: 0775
    #   with_items:
    #       - absent
    #       - directory
    #   # when: download.changed

    - name: Copy files to hosts
      copy:
        src: "{{ agent_installer_temp_local_dir }}/"
        dest: "{{ agent_installer_stage_dir }}"

    - name: Install agent_installer
      import_role:
        name: appdynamics.agent_installer.install
