- name: Download zfi agents
  hosts: vagrant
  #connection: local
  #run_once: yes
  tags: download
  tasks:
    - name: Ensure target dir is present # and empty
      file:
        path: ~/.appdynamics-agent_installer
        state: "{{ item }}"
        mode: 0775
      with_items:
          # - absent
          - directory
    - name: Download
      register: download
      appdynamics.agent_installer.download:
        client_id: "{{ client_id }}"
        client_secret: "{{ client_secret }}"
        controller_url: "{{ controller_url }}"
        dest: /home/vagrant/.appdynamics-agent_installer
      #check_mode: yes

    # - name: Download agents
    #   register: get_agents
    #   changed_when: false
    #   shell:
    #     chdir: ~/.appdynamics-agent_installer
    #     cmd: |
    #       {{ download.download_cmd }}
    # - name: Print output
    #   debug:
    #     msg: "{{ get_agents.stdout }}"

    # additional step to push archive
    # copy:

    # scope of role install_agent
    # use install API second time?

- name: Appdynamics install Zero Friction Installer Agent
  hosts: vagrant
  tags: install
  roles:
    - name: appdynamics.agent_installer.install
  vars:
    #appd_zfi_agent_distrib: /ansible_tower/zero-agent.tar
    agent_installer_stage_dir: /home/vagrant/.appdynamics-agent_installer
    agent_installer_install_path: /opt/appdynamics/agent_installer
    # agent_installer_enable_systemd: true
