---
- name: Converge
  hosts: all
  vars:
    agent_installer_temp_local_dir: /tmp/appdynamics-agent-installer
    agent_installer_stage_dir: /tmp/appdynamics-agent-installer-stage
  tasks:
    - name: Download
      register: download
      appdynamics.agent_installer.download:
        client_id: "{{ client_id }}"
        client_secret: "{{ client_secret }}"
        controller_url: "{{ controller_url }}"
        dest: "{{ agent_installer_stage_dir }}"
      #check_mode: yes

    - name: Install agent_installer
      import_role:
        name: appdynamics.agent_installer.install
      vars:
        agent_installer_user: vagrant
      tags: molecule-idempotence-notest
