---
- name: Prepare
  hosts: all
  tasks:
    - name: Install required packages
      become: true
      apt:
        name:
          - unzip
          - curl
        update_cache: yes
      when: ansible_os_family == 'Debian'
    - name: Install required packages
      become: true
      yum:
        name:
          - unzip
          - curl
      when: ansible_os_family == 'RedHat'
    - name: Create test_user
      become: true
      user:
        name: test_user
        state: present
