---
- name: Prepare
  hosts: all
  tasks:
    - name: Install required packages
      become: true
      package:
        name:
          - unzip
          - curl
    - name: Create test_user
      become: true
      user:
        name: test_user
        state: present
