- name: Install zfi agents
  hosts: vagrant
  vars:
    agent_installer_stage_dir_prefix: /tmp/appdynamics-agent-installer-stage
  tasks:
    - name: Download
      register: download
      appdynamics.agent_installer.download:
        client_id: "{{ client_id }}"
        client_secret: "{{ client_secret }}"
        controller_url: "{{ controller_url }}"
        dest: "{{ agent_installer_stage_dir_prefix }}"
      #check_mode: yes

    - name: Install agent_installer
      import_role:
        name: appdynamics.agent_installer.install
      vars: 
        agent_installer_stage_dir: "{{ agent_installer_stage_dir_prefix }}/{{ download.checksum }}"
