- name: Install zfi agents
  hosts: vagrant
  vars:
    agent_installer_temp_local_dir: /tmp/appdynamics-agent-installer
    agent_installer_stage_dir_prefix: /tmp/appdynamics-agent-installer-stage
  tasks:
    - name: Download
      run_once: yes
      delegate_to: localhost
      register: download
      appdynamics.agent_installer.download:
        client_id: "{{ client_id }}"
        client_secret: "{{ client_secret }}"
        controller_url: "{{ controller_url }}"
        dest: "{{ agent_installer_temp_local_dir }}"
      #check_mode: yes

    - name: Copy files to hosts
      copy:
        src: "{{ download.dest_subdir }}/"
        dest: "{{ agent_installer_stage_dir_prefix }}/{{ download.checksum }}"

    - name: Install agent_installer
      import_role:
        name: appdynamics.agent_installer.install
      vars: 
        agent_installer_stage_dir: "{{ agent_installer_stage_dir_prefix }}/{{ download.checksum }}"
