- name: Install zfi agents
  hosts: all
  vars_files: 
    - agent_installer_vars.yaml
  tasks:
    - name: Install agent_installer
      import_role:
        name: appdynamics.agent_installer.agent_installer