- name: Uninstall zeroagent
  become_user: "{{ appdynamics_zeroagent_user }}"
  become: yes
  command: 
    cmd: "{{ appdynamics_zeroagent_dir }}/bin/zeroctl uninstall"
    removes: "{{ appdynamics_zeroagent_dir }}/bin/zeroagent"
  ignore_errors: yes
  register: zeroagent_uninstall

- name: Clean zeroagent dir
  become_user: "{{ appdynamics_zeroagent_user }}"
  become: yes
  file:
    path: "{{ appdynamics_zeroagent_dir }}"
    state: absent
  when: zeroagent_uninstall.changed
  ignore_errors: yes
