name: "ansible-test"
on:
  pull_request:
  push:
defaults:
  run:
    working-directory: ansible_collections/appdynamics/agent_installer
jobs:
  ansible_test:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
    strategy:
      fail-fast: false
      matrix:
        test:
          - sanity
          - units
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: ansible_collections/appdynamics/agent_installer

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: python3 -m pip install ansible
      
      - name: Test the collection (${{ matrix.test }})
        run: |
           ansible-test ${{ matrix.test }} --docker default -v --color=yes
